SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:new_password@localhost:5432/castingagency'
SQLALCHEMY_UNIT_TEST_URI = 'postgresql://postgres:new_password@localhost:5432/castingagencytest'
LISTINGS_PER_PAGE = 8

bearer_tokens = {
  "casting_assistant": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZ3V1BsZ2dGVXVXemF2OVpCNGl0eCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQxMjM0NS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjBkNzhlNDVmMzVlNDIwMDcxOWMxNWY5IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyIsImlhdCI6MTYyNDc0MzU2OSwiZXhwIjoxNjI0NzUwNzY5LCJhenAiOiJoMFpnNWNoQXR4OWowWE84VmFpQmh1eGVnYmJkWEM3WiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiXX0.FxyLYk9uFhlesNTFQaXEkHeeH-en4qGnoLJGyBKsZcKOguiQI6K0V493dtprSRjeoJjiQi2eYGj2xVp0VDriK8d0YtWKhKxaANoGGaTN68GQO4nIdqnSUUTWZMMHOQx5fJPwl4fTAMZ4ae7szax2gmAmLqFaP_0vXK5QD1XZSMKJkwRByyGko3CPL5zwLNwVX6J32HEyNx0s-nsCxG0BcjVjddxdFirWSi85Vfg9f-7XAGaDLlMqAy0yxi5H0yeFAV-3j5ZSpTN1uIU_dP-Bq1gc8HM9z1XOJRqgTmXWXmaMWahfvvqkvSYfBRvkhBqL1Mde66u5Rygio-q0wKTh9Q",
  "executive_producer": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZ3V1BsZ2dGVXVXemF2OVpCNGl0eCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQxMjM0NS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjBjNGY3Nzc2MTJkODIwMDcwYTVlNjFjIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyIsImlhdCI6MTYyNDc0Mjk0NSwiZXhwIjoxNjI0NzUwMTQ1LCJhenAiOiJoMFpnNWNoQXR4OWowWE84VmFpQmh1eGVnYmJkWEM3WiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9yIiwiZGVsZXRlOm1vdmllIiwiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiLCJwYXRjaDphY3RvciIsInBhdGNoOm1vdmllIiwicG9zdDphY3RvciIsInBvc3Q6bW92aWUiXX0.nJMQXCymObyXvDsUphG4AJdDDl5Q9eTqLbNLxgAFi5s1178HBmtYzod_pwogjTn9pC7U9AzhwMJsuv_RsyqlIzX-pZcYaJIGjXuDIaUC6-GK-LMXBOOx4j4BTbLchHTBv3IavMPSkZTdV-qu8rBiKwM40TclatwBGVyN69nEXoPlccKl1QW94DFFmk2XS7wx3A1UEC_VDV92XUxmyc1wstp1CNbv7fsIo6u-FVgzyYe2FbkHqnkYbtCyzpyF10aH3wszl2lmtBfOCNFt11_N-HLSUDhYHC-pn_GxGUKqGwd18Yfyk8iEBnpjKozz5-ExceD2hSww8jauatqegiIhkg",
  "casting_director": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZ3V1BsZ2dGVXVXemF2OVpCNGl0eCJ9.eyJpc3MiOiJodHRwczovL2ZzbmQxMjM0NS51cy5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NjBkNzhkZmYzODUxZDMwMDY5MmViOTQ5IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwLyIsImlhdCI6MTYyNDc0MzQ2NiwiZXhwIjoxNjI0NzUwNjY2LCJhenAiOiJoMFpnNWNoQXR4OWowWE84VmFpQmh1eGVnYmJkWEM3WiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9yIiwiZ2V0OmFjdG9ycyIsImdldDptb3ZpZXMiLCJwYXRjaDphY3RvciIsInBhdGNoOm1vdmllIiwicG9zdDphY3RvciJdfQ.dR1YlAKATG2E7hXoTW_UMJ4a9QXMQ9iwv3qnaWSn82WzTJO47yAO8a5kvPgcJhSJofilQzSZs4HO9bogY1m-3_Ek8cMGPaxn6ZCJuVm9GIXZ74I5sKntT0gzBHfhonjM8ARL_vhTploLUWjMc0vfG9cif4NaaoGq7nJ4nid_2AZpz5R0GDYasz03RzmNNiof0s3lQufdGd1kbLhLsrHgwmxtksSZ3evw7_sWin9cv9Uei0eybEpaycfwD0bAQNcEHGpEra8yib3mMk1OFhA_x2cEmto4fq-XmIQ436oJIer9Nlq8Yd8OKxVEOHx66-VzddIKsrXCbbqvAlUprSCogA"
}

"""

https://YOUR_DOMAIN/authorize?
  response_type=code|token&
  client_id=YOUR_CLIENT_ID&
  connection=CONNECTION&
  redirect_uri=https://YOUR_APP/callback&
  state=STATE&
  ADDITIONAL_PARAMETERS
  
https://fsnd12345.us.auth0.com/authorize?audience=http://localhost:5000/&response_type=token&client_id=h0Zg5chAtx9j0XO8VaiBhuxegbbdXC7Z&redirect_uri=https://127.0.0.1:8080/actors

"""

# paginate results
def paginate_results(request, selections):
  page = request.args.get('page', 1, type=int)
  start = (page - 1) * LISTINGS_PER_PAGE
  end = start + LISTINGS_PER_PAGE
  listings = [listing.format() for listing in selections]
  current_listings = listings[start:end]

  return current_listings